SgwAdmin.Request = DS.Model.extend({
  firstName: DS.attr('string'),
  email: DS.attr('string'),
  primaryPhone: DS.attr('string'),
  design: DS.attr('string'),
  stock: DS.attr('string'),
  height: DS.attr('string'),
  width: DS.attr('string'),
  description: DS.attr('string'),
  image: DS.attr('string'),
  installation: DS.attr('string'),
  framing: DS.attr('string'),
  date: DS.attr('date')
});

SgwAdmin.Request.FIXTURES = [
  {
    id: 12,
    firstName: 'John Baird',
    email: 'j.baird@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/31/2014'
  },
  {
    id: 11,
    firstName: 'Lynn Martel',
    email: 'Lmartel25@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/28/2014'
  },
  {
    id: 10,
    firstName: 'Louis Sanchez',
    email: 'mrsanchez@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/24/2014'
  },
  {
    id: 9,
    firstName: 'Linda Maxwell',
    email: 'li.max@hotmail.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/24/2014'
  },
  {
    id: 8,
    firstName: 'Tina Thompson',
    email: 'thomspon@gmail.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/23/2014'
  },
  {
    id: 7,
    firstName: 'Lynn Martel',
    email: 'Lmartel25@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/21/2014'
  },
  {
    id: 6,
    firstName: 'Brenda Higgs',
    email: 'brenhiggs@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/19/2014'
  },
  {
    id: 5,
    firstName: 'John Rodriguez',
    email: 'j.rodriguez84@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/14/2014'
  },
  {
    id: 4,
    firstName: 'Amanda Becking',
    email: 'amanda.beck@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/11/2014'
  },
  {
    id: 3,
    firstName: 'Sarah Miller',
    email: 'miller.sarah@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/09/2014'
  },
  {
    id: 2,
    firstName: 'Linda Bowing',
    email: 'linda.bowing@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/08/2014'
  },
  {
    id: 1,
    firstName: 'Tamara Mayer',
    email: 'tammy12@aol.com',
    primaryPhone: '7742664858',
    design: 'I would like a custom pattern designed by your artists',
    stock: 'Item #6646',
    height: '21 1/2',
    width: '33 3/4',
    description: 'I have a sun room that we have turned into a spare room. There is a framed opening and when you walk down the stairs you can see in the room and the bed. I want to put in the stained glass window for some privacy and I am looking for a quote.',
    image: 'http://upload.wikimedia.org/wikipedia/commons/3/3e/Temple_Ohev_Sholom_Stained_Glass,_Ascalon_Studios,_David_Ascalon.jpg',
    installation: 'I m going to mount the window into a frame',
    framing: 'Minimal Install: The stained glass rests against your existing window and is held in place by tacking, quarter round or molding.',
    date: '07/08/2014'
  },
];